version: '3.7'
services: 
    api: 
        image: node:alpine
        container_name: api_nodejs
        restart: on-failure
        ports: 
            - "80:8080"
        depends_on: 
            - mongo
        volumes: 
            - ./api:/app/
        working_dir: /app
        env_file: .env
        environment: 
            MONGO_HOSTNAME: $MONGO_HOSTNAME
            MONGO_PORT: $MONGO_PORT
            MONGO_USERNAME: $MONGO_USERNAME
            MONGO_PASSWORD: $MONGO_PASSWORD
        command: /bin/sh -c "npm install && npm run dev"
    
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment: 
            ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
            ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
        depends_on: 
            - mongo

    mongo:
        image: mongo
        container_name: mongo
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD