version: '3'
services: 
    api: 
        image: node:alpine
        container_name: api_nodejs
        restart: on-failure
        ports: 
            - "80:8080"
        links: 
            - db
        depends_on: 
            - db
        volumes: 
            - ./:/app/
        working_dir: /app
        env_file: .env
        environment: 
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
            - MONGO_HOSTNAME=$MONGO_HOSTNAME
            - MONGO_PORT=$MONGO_PORT
        command: npm run dev
    
    db:
        image: mongo:4.0
        container_name: db_mongo
        restart: always
        expose: 
            - 27017
        volumes: 
            - dbdata:/data/db


volumes: 
    dbdata: