version: '3'
services: 
    api: 
        image: node:alpine
        container_name: api_nodejs
        restart: on-failure
        ports: 
            - "80:8080"
        depends_on: 
            - db
        volumes: 
            - ./:/app/
        working_dir: /app
        env_file: .env
        environment: 
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
            - MONGO_HOSTNAME=$MONGO_HOSTNAME
            - MONGO_PORT=$MONGO_PORT
        command: npm run dev
        networks: 
            - api_to_db
    
    db:
        image: mvertes/alpine-mongo
        container_name: db_mongo
        restart: always
        expose: 
            - 27017
        env_file: .env
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        volumes: 
            - dbdata:/data/db
        networks: 
            - api_to_db

networks: 
    api_to_db:
        driver: bridge
volumes: 
    dbdata: