version: '3'
services: 
    api: 
        image: node:alpine
        restart: on-failure
        ports: 
            - "80:8080"
        volumes: 
            - ./:/app/
        working_dir: /app
        command: npm run dev